# Generated by Django 4.2.13 on 2024-09-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_cluster_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clustername', models.CharField(max_length=255)),
                ('cluster_status', models.CharField(choices=[('failed', 'Failed'), ('deleted', 'Deleted'), ('completed', 'Completed')], max_length=10)),
                ('deleted_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
