# Generated by Django 4.2.13 on 2024-09-03 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_api', '0005_clusterhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clustername', models.CharField(max_length=255)),
                ('cluster_status', models.CharField(choices=[('failed', 'Failed'), ('deleted', 'Deleted'), ('completed', 'Completed')], max_length=10)),
                ('deleted_time', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ClusterHistory',
        ),
    ]
