# Generated by Django 4.2.13 on 2024-09-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0006_cluster_history_delete_clusterhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBcredentials',
        ),
    ]
