# Generated by Django 3.2.25 on 2024-10-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0007_delete_dbcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='pg_db_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
