# Generated by Django 3.2.25 on 2024-10-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0009_alter_cluster_backup_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='pg_db_name',
        ),
    ]
